### ISSUE TITLE
gluster volume group profile functionality in GD2

### ISSUE THREAD

**Issue by atinmu** [gluster/glusterd2#454] opened 2017-11-28 12:39 UTC
Just like GD1 has the group profile option to set multiple options at one go for a volume GD2 needs to have the same.

**Comment by atinmu** [comment] 2018-01-02 07:46
As we discussed, we should provide APIs to allow users to define their own custom profiles. For all the default and tested profiles like virt, md-cache I don't think it makes much sense to allow users to tweak in the parameters but for custom profiles it does. Also along with that, an API to unset such profiles would be very good to have. Additionally if one can use an API to view what all tunables are part of a custom profile it'd be ideal.

**Comment by atinmu** [comment] 2018-01-29 04:16
@kmlmhnn  @prashanthpai Can this issue be closed? Do we have the ReST API documented in the wiki?

**Comment by prashanthpai** [comment] 2018-01-29 04:43
> Can this issue be closed? 

Yes.

> Do we have the ReST API documented in the wiki?

Not yet. Updating the wiki is manual now, unfortunately. We'll work on to automate this.

**Comment by atinmu** [comment] 2018-02-06 02:31
@kmlmhnn Can you please document the APIs in the wiki and take this issue to the closure?

**Comment by kmlmhnn** [comment] 2018-02-07 04:11
@atinmu Done.

**Comment by atinmu** [comment] 2018-02-18 04:47
@kmlmhnn Is there a functionality added by which the same group profile options can be reset at one go? If yes, then this issue can be closed otherwise we need to work on that part as well.

**Comment by kmlmhnn** [comment] 2018-02-19 18:33
@atinmu You can for eg: do a `glustercli volume set <volname> <profile> off` and all the individual options set by `<profile>` will be reset back to their default values.

**Comment by poornimag** [comment] 2018-04-06 11:08
#326

**Comment by atinmu** [comment] 2018-06-27 04:52
@poornimag @aravindavk  Is there anything pending for this? If not we need to close this one.

**Comment by prashanthpai** [comment] 2018-06-27 08:57
This is a duplicate of issue #614

**Closed by prashanthpai** 2018-06-27 08:57 UTC
Labels: FW: ReST, GCS-Blocker, Gluster 4.2, priority: high
