### ISSUE TITLE
Flexible volgen

### ISSUE THREAD

**Issue by kshlm** [gluster/glusterd2#133] opened 2016-09-22 12:37 UTC
Volgen in GD1 is really inflexible, requiring changes to the source code to modify the structure of the volume graph.

The current implementation in GD2 is directly inspired by the old GD volgen and isn't flexible.

The new volgen needs to be,
- Flexible, allow graph structures to be easily defined without changes to the GD2 source code
- Pluggable, allow other developers to easily add/remove their new xlators into the graph without changes to GD2 source code

**Comment by kshlm** [comment] 2016-09-22 13:23
We had discussed this earlier this year, when a bunch of GlusterFS developers got together in Brno during DevConf16.

This [etherpad][1] has details that were captured during the discussions. I'll open a wiki with the details from the pad.

[1]: https://public.pad.fsfe.org/p/gluster-gd2-kaushal

**Comment by kshlm** [comment] 2016-09-22 13:31
Created a wiki [page](https://github.com/gluster/glusterd2/wiki/Flexible-Volgen)  with the information from the pad.

**Comment by prashanthpai** [comment] 2016-12-26 06:46
Can close this as duplicate of #163 ?

**Closed** 2017-02-27 11:13 UTC
Labels: feature, FW: Volgen
