### ISSUE TITLE
Add volume capacity to Volinfo response

### ISSUE THREAD

**Issue by kshlm** [gluster/glusterd2#1136] opened 2018-08-06 14:07 UTC
CSI requires a ListVolumes API that needs to list all provisioned volumes. At the moment the GD2 based CSI driver (gluster/gluster-csi-driver) does this by first getting the list of all volumes and then calling volume-status on each separately. This process will break down when dealing with a really large number of volumes.

**Comment by harigowtham** [comment] 2018-08-23 11:01
v1/volumes/testvol/status gives the output for a particular volume. while the v1/volumes call gives an array of the result containing each volume. 

Example of each:
[root@fedora3 glusterd2]# curl -i -X GET http://192.168.122.18:24007/v1/volumes
HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
X-Gluster-Cluster-Id: 4bf15b1f-4c0d-4b15-8eed-5cb0f3e1acf6
X-Gluster-Peer-Id: e5adc961-3917-403e-ac83-30815be5caa5
X-Request-Id: ace7a4eb-53ae-4bab-ac6f-5a8e4ec6bffd
Date: Thu, 23 Aug 2018 10:15:45 GMT
Content-Length: 1147

[{"id":"fee943d2-5a8f-427b-b402-cabbdf3c2e3a","name":"testvol","type":"Distribute","transport":"tcp","distribute-count":1,"replica-count":0,"arbiter-count":0,"options":{},"state":"Started","subvols":[{"name":"testvol-distribute-0","type":"Distribute","bricks":[{"id":"f9132bbe-390f-403b-96a2-074ae6d7fa92","path":"/data/gluster/bricks/b1","volume-id":"fee943d2-5a8f-427b-b402-cabbdf3c2e3a","volume-name":"testvol","peer-id":"e5adc961-3917-403e-ac83-30815be5caa5","host":"192.168.122.18","type":"Brick"}],"replica-count":1,"arbiter-count":0}],"metadata":{},"snap-list":[]},{"id":"aa3ffde0-ecb3-44fd-86e7-8ea070bce4a9","name":"testvol1","type":"Distribute","transport":"tcp","distribute-count":1,"replica-count":0,"arbiter-count":0,"options":{},"state":"Started","subvols":[{"name":"testvol1-distribute-0","type":"Distribute","bricks":[{"id":"0f2498a5-d338-43ec-8c2d-aaacdc423c02","path":"/data/gluster/bricks/b2","volume-id":"aa3ffde0-ecb3-44fd-86e7-8ea070bce4a9","volume-name":"testvol1","peer-id":"e5adc961-3917-403e-ac83-30815be5caa5","host":"192.168.122.18","type":"Brick"}],"replica-count":1,"arbiter-count":0}],"metadata":{},"snap-list":[]}]

The above has returned an array.

while the status command's API return for that particular volume:
[root@fedora3 glusterd2]# curl -i -X GET http://192.168.122.18:24007/v1/volumes/testvol/status
HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
X-Gluster-Cluster-Id: 4bf15b1f-4c0d-4b15-8eed-5cb0f3e1acf6
X-Gluster-Peer-Id: e5adc961-3917-403e-ac83-30815be5caa5
X-Request-Id: 686cc7a3-942c-4882-89c7-708f48d6c32d
Date: Thu, 23 Aug 2018 10:15:44 GMT
Content-Length: 634

{"info":{"id":"fee943d2-5a8f-427b-b402-cabbdf3c2e3a","name":"testvol","type":"Distribute","transport":"tcp","distribute-count":1,"replica-count":0,"arbiter-count":0,"options":{},"state":"Started","subvols":[{"name":"testvol-distribute-0","type":"Distribute","bricks":[{"id":"f9132bbe-390f-403b-96a2-074ae6d7fa92","path":"/data/gluster/bricks/b1","volume-id":"fee943d2-5a8f-427b-b402-cabbdf3c2e3a","volume-name":"testvol","peer-id":"e5adc961-3917-403e-ac83-30815be5caa5","host":"192.168.122.18","type":"Brick"}],"replica-count":1,"arbiter-count":0}],"metadata":{},"snap-list":[]},"online":true,"size":{"capacity":0,"used":0,"free":0}}

My initial implementation was to give the output similar to the /v1/volumes API call. As its already available I understood there might be changes in the request. Do let me know the changes that are expected, So i can work on it.

And also whether to come up with a new command for it or add it on to the v1/volumes API call.

**Comment by harigowtham** [comment] 2018-08-23 11:55
As per the usecase the volume capacity is necessary not the usage. Volume info doesn't get the capacity as of now. Will make the changes for the GD2 to maintain the capacity of each volume. so that the volume info can get the capacity as needed by the CSI driver.

**Comment by aravindavk** [comment] 2018-08-23 12:03
Looks like duplicate of https://github.com/gluster/glusterd2/issues/1081

**Comment by aravindavk** [comment] 2018-10-04 07:51
This PR adds Volume capacity for auto provisioned volumes. Closing this issue now, please open new issue if Volume size is required for manual provisioned volumes as well https://github.com/gluster/glusterd2/pull/1193

**Closed by aravindavk** 2018-10-04 07:51 UTC
Labels: GCS-Stretch, priority: medium, usability
