### ISSUE TITLE
Volume start force command causes to all bricks offline

### ISSUE THREAD

**Issue by rmadaka** [gluster/glusterd2#791] opened 2018-05-24 12:30 UTC
-> Create volume
-> killing one brick 
-> then perform the volume start force command
-> volume start force command failed and all bricks went to offline of that volume
-> Then again perform the volume start force command
-> All bricks came to online of that volume.

commands output:

./glustercli volume status
Volume : rep1
+--------------------------------------+--------------+---------------------+--------+-------+-------+
|               BRICK ID               |     HOST     |        PATH         | ONLINE | PORT  |  PID  |
+--------------------------------------+--------------+---------------------+--------+-------+-------+
| eab65f4e-cbcc-4b36-ad3c-9c53344fb229 | 10.70.35.235 | /bricks/brick0/rep1 | true   | 49164 | 24418 |
| 609af534-7c58-4d0f-8168-bc57b37b4875 | 10.70.35.194 | /bricks/brick0/rep1 | true   | 49164 | 14731 |
| 253f33dd-9cf6-4c09-9934-85aa14d049f9 | 10.70.35.219 | /bricks/brick0/rep1 | true   | 49164 |  1783 |
+--------------------------------------+--------------+---------------------+--------+-------+-------+

 kill -9 1783
[root@dhcp35-219 ~]# ./glustercli volume status rep1
Volume : rep1
+--------------------------------------+--------------+---------------------+--------+-------+-------+
|               BRICK ID               |     HOST     |        PATH         | ONLINE | PORT  |  PID  |
+--------------------------------------+--------------+---------------------+--------+-------+-------+
| 253f33dd-9cf6-4c09-9934-85aa14d049f9 | 10.70.35.219 | /bricks/brick0/rep1 | false  |     0 |     0 |
| eab65f4e-cbcc-4b36-ad3c-9c53344fb229 | 10.70.35.235 | /bricks/brick0/rep1 | true   | 49164 | 24418 |
| 609af534-7c58-4d0f-8168-bc57b37b4875 | 10.70.35.194 | /bricks/brick0/rep1 | true   | 49164 | 14731 |
+--------------------------------------+--------------+---------------------+--------+-------+-------+
[root@dhcp35-219 ~]# ./glustercli volume start rep1 force
volume start failed

Error: Request failed with HTTP Status code 500
Process is already running
[root@dhcp35-219 ~]# ./glustercli volume status rep1
Volume : rep1
+--------------------------------------+--------------+---------------------+--------+------+-----+
|               BRICK ID               |     HOST     |        PATH         | ONLINE | PORT | PID |
+--------------------------------------+--------------+---------------------+--------+------+-----+
| 253f33dd-9cf6-4c09-9934-85aa14d049f9 | 10.70.35.219 | /bricks/brick0/rep1 | false  |    0 |   0 |
| eab65f4e-cbcc-4b36-ad3c-9c53344fb229 | 10.70.35.235 | /bricks/brick0/rep1 | false  |    0 |   0 |
| 609af534-7c58-4d0f-8168-bc57b37b4875 | 10.70.35.194 | /bricks/brick0/rep1 | false  |    0 |   0 |
+--------------------------------------+--------------+---------------------+--------+------+-----+
[root@dhcp35-219 ~]# ./glustercli volume start rep1 force
Volume rep1 started successfully
[root@dhcp35-219 ~]# ./glustercli volume status rep1
Volume : rep1
+--------------------------------------+--------------+---------------------+--------+-------+-------+
|               BRICK ID               |     HOST     |        PATH         | ONLINE | PORT  |  PID  |
+--------------------------------------+--------------+---------------------+--------+-------+-------+
| 609af534-7c58-4d0f-8168-bc57b37b4875 | 10.70.35.194 | /bricks/brick0/rep1 | true   | 49179 | 14934 |
| 253f33dd-9cf6-4c09-9934-85aa14d049f9 | 10.70.35.219 | /bricks/brick0/rep1 | true   | 49181 |  2060 |
| eab65f4e-cbcc-4b36-ad3c-9c53344fb229 | 10.70.35.235 | /bricks/brick0/rep1 | true   | 49179 | 24616 |
+--------------------------------------+--------------+---------------------+--------+-------+-------+

**Comment by Madhu-1** [comment] 2018-05-29 09:48
@rmadaka  am not able to reproduce this issue with new glusterd2.

can you provide glusterd2  logs from all nodes for this issue?

you should use --force flag to start volume forcefully 

```./glustercli volume start rep1 ---force
```

**Comment by atinmu** [comment] 2018-06-22 08:23
Need retest and also a reproducer with all the logs

**Comment by Madhu-1** [comment] 2018-07-05 12:32
I Have raised the same issue #931   @prashanthpai I think this is not completely fixed

**Comment by Madhu-1** [comment] 2018-07-05 12:49
@prashanthpai  can you move out this of this sprint, as we are not able to reproduce the original issue, we are facing a new issue here

**Comment by prashanthpai** [comment] 2018-07-05 12:50
@rmadaka I'm not looking at this issue yet. At a quick glance at this, I saw, use of `kill -9` which sends a `SIGKILL` and not a `SIGTERM`. Please try to reproduce this with a `SIGTERM`. See man page of kill command for more details

**Comment by rmadaka** [comment] 2018-07-06 06:22
@aravindavk : Here brick process are not going down, port-id became '0'

**Comment by Akarsha-rai** [comment] 2018-08-30 09:27
I came across the same scenario, where I killed one brick and tried starting volume with force option observed same behavior. 

Steps:
1) Created replica 3 volume and started it
```
glustercli volume status
Volume : testvol
+--------------------------------------+--------------+------------------------+--------+-------+------+
|               BRICK ID               |     HOST     |          PATH          | ONLINE | PORT  | PID  |
+--------------------------------------+--------------+------------------------+--------+-------+------+
| fe839316-10cf-4ed0-a80d-b73efba4e4c4 | 10.70.35.19  | /bricks/brick2/testvol | true   | 49153 | 1587 |
| 1086edad-261e-4aee-8f12-90eb0cf236be | 10.70.35.229 | /bricks/brick1/testvol | true   | 49152 | 1618 |
| 763d8647-cc80-465d-9936-783421212210 | 10.70.35.163 | /bricks/brick1/testvol | true   | 49152 | 1562 |
| 08083982-aacf-419f-8cdf-b36a08923e5a | 10.70.35.19  | /bricks/brick1/testvol | true   | 49152 | 1564 |
| c90ae216-c4d8-472e-8246-0ddbf8b86967 | 10.70.35.229 | /bricks/brick2/testvol | true   | 49153 | 1640 |
| e88d54b7-98f1-40f3-8bc3-ea408e592350 | 10.70.35.163 | /bricks/brick2/testvol | true   | 49153 | 1585 |
+--------------------------------------+--------------+------------------------+--------+-------+------+
```
2) Killing one brick
```
 kill 1618
```
Volume status:
```
glustercli volume status
Volume : testvol
+--------------------------------------+--------------+------------------------+--------+-------+------+
|               BRICK ID               |     HOST     |          PATH          | ONLINE | PORT  | PID  |
+--------------------------------------+--------------+------------------------+--------+-------+------+
| 1086edad-261e-4aee-8f12-90eb0cf236be | 10.70.35.229 | /bricks/brick1/testvol | false  |     0 |    0 |
| 763d8647-cc80-465d-9936-783421212210 | 10.70.35.163 | /bricks/brick1/testvol | true   | 49152 | 1562 |
| 08083982-aacf-419f-8cdf-b36a08923e5a | 10.70.35.19  | /bricks/brick1/testvol | true   | 49152 | 1564 |
| c90ae216-c4d8-472e-8246-0ddbf8b86967 | 10.70.35.229 | /bricks/brick2/testvol | true   | 49153 | 1640 |
| e88d54b7-98f1-40f3-8bc3-ea408e592350 | 10.70.35.163 | /bricks/brick2/testvol | true   | 49153 | 1585 |
| fe839316-10cf-4ed0-a80d-b73efba4e4c4 | 10.70.35.19  | /bricks/brick2/testvol | true   | 49153 | 1587 |
+--------------------------------------+--------------+------------------------+--------+-------+------+
```
3) Volume started with force option
```
glustercli volume start testvol --force
Volume testvol started successfully
```
4) Checked volume status from all nodes(same output from all nodes)
```
glustercli volume status
Volume : testvol
+--------------------------------------+--------------+------------------------+--------+-------+------+
|               BRICK ID               |     HOST     |          PATH          | ONLINE | PORT  | PID  |
+--------------------------------------+--------------+------------------------+--------+-------+------+
| 1086edad-261e-4aee-8f12-90eb0cf236be | 10.70.35.229 | /bricks/brick1/testvol | true   | 49152 | 1758 |
| 763d8647-cc80-465d-9936-783421212210 | 10.70.35.163 | /bricks/brick1/testvol | true   |     0 | 1562 |
| 08083982-aacf-419f-8cdf-b36a08923e5a | 10.70.35.19  | /bricks/brick1/testvol | true   |     0 | 1564 |
| c90ae216-c4d8-472e-8246-0ddbf8b86967 | 10.70.35.229 | /bricks/brick2/testvol | true   |     0 | 1640 |
| e88d54b7-98f1-40f3-8bc3-ea408e592350 | 10.70.35.163 | /bricks/brick2/testvol | true   |     0 | 1585 |
| fe839316-10cf-4ed0-a80d-b73efba4e4c4 | 10.70.35.19  | /bricks/brick2/testvol | true   |     0 | 1587 |
+--------------------------------------+--------------+------------------------+--------+-------+------+
```
5) Retried volume start with force and checked volume status(same output from all nodes)
```
glustercli volume status
Volume : testvol
+--------------------------------------+--------------+------------------------+--------+------+------+
|               BRICK ID               |     HOST     |          PATH          | ONLINE | PORT | PID  |
+--------------------------------------+--------------+------------------------+--------+------+------+
| 1086edad-261e-4aee-8f12-90eb0cf236be | 10.70.35.229 | /bricks/brick1/testvol | true   |    0 | 1758 |
| 763d8647-cc80-465d-9936-783421212210 | 10.70.35.163 | /bricks/brick1/testvol | true   |    0 | 1562 |
| 08083982-aacf-419f-8cdf-b36a08923e5a | 10.70.35.19  | /bricks/brick1/testvol | true   |    0 | 1564 |
| c90ae216-c4d8-472e-8246-0ddbf8b86967 | 10.70.35.229 | /bricks/brick2/testvol | true   |    0 | 1640 |
| e88d54b7-98f1-40f3-8bc3-ea408e592350 | 10.70.35.163 | /bricks/brick2/testvol | true   |    0 | 1585 |
| fe839316-10cf-4ed0-a80d-b73efba4e4c4 | 10.70.35.19  | /bricks/brick2/testvol | true   |    0 | 1587 |
+--------------------------------------+--------------+------------------------+--------+------+------+
```

Information about the environment:
```
Glusterd2 version used (e.g. v4.1.0 or master):
[root@dhcp35-181 ~]# rpm -qa | grep glusterd2
glusterd2-4.1.0-164.gite8ebe18.el7.x86_64

Operating system used:
[root@dhcp35-181 ~]# cat /etc/centos-release
CentOS Linux release 7.5.1804 (Core)

Glusterd2 compiled from sources, as a package (rpm/deb), or container:
package

Using External ETCD: (yes/no, if yes ETCD version):
yes, etcdmain: etcd Version: 3.3.8

If container, which container image:

Using kubernetes, openshift, or direct install:
direct install

If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside:
```
Other useful information
```
glusterd2 config files from all nodes (default /etc/glusterd2/glusterd2.toml)
[root@dhcp35-229 ~]# cat /etc/glusterd2/glusterd2.toml

localstatedir = "/var/lib/glusterd2"
logdir = "/var/log/glusterd2"
logfile = "glusterd2.log"
loglevel = "INFO"
rundir = "/var/run/glusterd2"
defaultpeerport = "24008"
peeraddress = ":24008"
clientaddress = ":24007"
#restauth should be set to false to disable REST authentication in glusterd2
restauth = false
etcdendpoints = "http://10.70.35.10:2379"
noembed = true

[root@dhcp35-163 ~]# cat /etc/glusterd2/glusterd2.toml

localstatedir = "/var/lib/glusterd2"
logdir = "/var/log/glusterd2"
logfile = "glusterd2.log"
loglevel = "INFO"
rundir = "/var/run/glusterd2"
defaultpeerport = "24008"
peeraddress = ":24008"
clientaddress = ":24007"
#restauth should be set to false to disable REST authentication in glusterd2
restauth = false
etcdendpoints = "http://10.70.35.10:2379"
noembed = true

[root@dhcp35-19 ~]# cat /etc/glusterd2/glusterd2.toml

localstatedir = "/var/lib/glusterd2"
logdir = "/var/log/glusterd2"
logfile = "glusterd2.log"
loglevel = "INFO"
rundir = "/var/run/glusterd2"
defaultpeerport = "24008"
peeraddress = ":24008"
clientaddress = ":24007"
#restauth should be set to false to disable REST authentication in glusterd2
restauth = false
etcdendpoints = "http://10.70.35.10:2379"
noembed = true
```

Output of ps -ax | grep gluster from all nodes:
```
[root@dhcp35-229 ~]# ps -ax | grep gluster
 1275 ?        Ssl    0:04 /usr/sbin/glusterd2 --config=/etc/glusterd2/glusterd2.toml
 1640 ?        Ssl    0:00 /usr/sbin/glusterfsd --volfile-server 127.0.0.1 --volfile-server-port 24007 --volfile-id testvol.a2855277-c88c-4313-b8a8-2102f2d952b4.bricks-brick2-testvol -p /var/run/glusterd2/a2855277-c88c-4313-b8a8-2102f2d952b4-bricks-brick2-testvol.pid -S /var/run/glusterd2/d4ae07fdff17663f.socket --brick-name /bricks/brick2/testvol --brick-port 49153 -l /var/log/glusterd2/glusterfs/bricks/bricks-brick2-testvol.log --xlator-option *-posix.glusterd-uuid=a2855277-c88c-4313-b8a8-2102f2d952b4 --xlator-option testvol-server.transport.socket.listen-port=49153
 1758 ?        Ssl    0:00 /usr/sbin/glusterfsd --volfile-server 127.0.0.1 --volfile-server-port 24007 --volfile-id testvol.a2855277-c88c-4313-b8a8-2102f2d952b4.bricks-brick1-testvol -p /var/run/glusterd2/a2855277-c88c-4313-b8a8-2102f2d952b4-bricks-brick1-testvol.pid -S /var/run/glusterd2/b931a3024f5320bc.socket --brick-name /bricks/brick1/testvol --brick-port 49152 -l /var/log/glusterd2/glusterfs/bricks/bricks-brick1-testvol.log --xlator-option *-posix.glusterd-uuid=a2855277-c88c-4313-b8a8-2102f2d952b4 --xlator-option testvol-server.transport.socket.listen-port=49152
 2072 pts/0    S+     0:00 grep --color=auto gluster

[root@dhcp35-163 ~]# ps -ax | grep gluster
 1233 ?        Ssl    0:03 /usr/sbin/glusterd2 --config=/etc/glusterd2/glusterd2.toml
 1562 ?        Ssl    0:00 /usr/sbin/glusterfsd --volfile-server 127.0.0.1 --volfile-server-port 24007 --volfile-id testvol.6b200d2d-e606-4b41-ad80-211b13701bf3.bricks-brick1-testvol -p /var/run/glusterd2/6b200d2d-e606-4b41-ad80-211b13701bf3-bricks-brick1-testvol.pid -S /var/run/glusterd2/9157ad7883bac604.socket --brick-name /bricks/brick1/testvol --brick-port 49152 -l /var/log/glusterd2/glusterfs/bricks/bricks-brick1-testvol.log --xlator-option *-posix.glusterd-uuid=6b200d2d-e606-4b41-ad80-211b13701bf3 --xlator-option testvol-server.transport.socket.listen-port=49152
 1585 ?        Ssl    0:00 /usr/sbin/glusterfsd --volfile-server 127.0.0.1 --volfile-server-port 24007 --volfile-id testvol.6b200d2d-e606-4b41-ad80-211b13701bf3.bricks-brick2-testvol -p /var/run/glusterd2/6b200d2d-e606-4b41-ad80-211b13701bf3-bricks-brick2-testvol.pid -S /var/run/glusterd2/fd7f54f341086c11.socket --brick-name /bricks/brick2/testvol --brick-port 49153 -l /var/log/glusterd2/glusterfs/bricks/bricks-brick2-testvol.log --xlator-option *-posix.glusterd-uuid=6b200d2d-e606-4b41-ad80-211b13701bf3 --xlator-option testvol-server.transport.socket.listen-port=49153
 1943 pts/0    S+     0:00 grep --color=auto gluster

[root@dhcp35-19 ~]# ps -ax | grep gluster
 1236 ?        Ssl    0:03 /usr/sbin/glusterd2 --config=/etc/glusterd2/glusterd2.toml
 1564 ?        Ssl    0:00 /usr/sbin/glusterfsd --volfile-server 127.0.0.1 --volfile-server-port 24007 --volfile-id testvol.7f631335-8c92-4672-aa35-4a8bc521d66f.bricks-brick1-testvol -p /var/run/glusterd2/7f631335-8c92-4672-aa35-4a8bc521d66f-bricks-brick1-testvol.pid -S /var/run/glusterd2/c3f4a0795cfecefb.socket --brick-name /bricks/brick1/testvol --brick-port 49152 -l /var/log/glusterd2/glusterfs/bricks/bricks-brick1-testvol.log --xlator-option *-posix.glusterd-uuid=7f631335-8c92-4672-aa35-4a8bc521d66f --xlator-option testvol-server.transport.socket.listen-port=49152
 1587 ?        Ssl    0:00 /usr/sbin/glusterfsd --volfile-server 127.0.0.1 --volfile-server-port 24007 --volfile-id testvol.7f631335-8c92-4672-aa35-4a8bc521d66f.bricks-brick2-testvol -p /var/run/glusterd2/7f631335-8c92-4672-aa35-4a8bc521d66f-bricks-brick2-testvol.pid -S /var/run/glusterd2/2efdffd7001c68e5.socket --brick-name /bricks/brick2/testvol --brick-port 49153 -l /var/log/glusterd2/glusterfs/bricks/bricks-brick2-testvol.log --xlator-option *-posix.glusterd-uuid=7f631335-8c92-4672-aa35-4a8bc521d66f --xlator-option testvol-server.transport.socket.listen-port=49153
 1942 pts/0    S+     0:00 grep --color=auto gluster
```
Logs:
[node1.log](https://github.com/gluster/glusterd2/files/2335493/node1.log)
[node2.log](https://github.com/gluster/glusterd2/files/2335494/node2.log)
[node3.log](https://github.com/gluster/glusterd2/files/2335495/node3.log)

**Comment by vpandey-RH** [comment] 2018-08-30 09:54
@Akarsha-rai I am looking into it.

**Comment by vpandey-RH** [comment] 2018-09-11 06:59
@rmadaka  @Akarsha-rai  A fix has been merged for this issue. I guess this can be closed now.

**Comment by prashanthpai** [comment] 2018-09-11 09:18
@Akarsha-rai We'll close this after you verify the fix with the latest build

**Comment by Akarsha-rai** [comment] 2018-09-11 13:04
@prashanthpai , I have tested it and works as expected.

**Comment by prashanthpai** [comment] 2018-09-11 15:49
Thank you @Akarsha-rai

**Closed by prashanthpai** 2018-09-11 15:49 UTC
Labels: FW: Volume Management, GCS-Blocker, Gluster 4.2, bug, need-info, priority: high
