### ISSUE TITLE
Stop unnecessary vendoring until MVP or stable

### ISSUE THREAD

**Issue by purpleidea** [gluster/glusterd2#275] opened 2017-02-28 06:32 UTC
I really don't understand why there is all of this vendoring going on!

https://github.com/gluster/glusterd2/blob/master/glide.lock

This is great for slow moving projects, but not good before Glusterd2 is minimally viable (MVP) or pre-stable!

Please can we kill this?

**Comment by purpleidea** [comment] 2017-02-28 06:33
(and if not, an explanation about why we're doing this would be much appreciated!!)

**Comment by kshlm** [comment] 2017-02-28 08:30
Vendoring is staying, and will not be removed. Period.

We had problems with some fast moving dependencies. We spent time trying to fix issues caused by developers having different versions of the dependencies, and the CI always trying to use the latest versions.

Once we vendored, we could actually proceed doing things we wanted to do rather than fighting dependencies. Vendoring allows us to keep the build environment same everywhere, so we know when something goes wrong, its not the environment that caused it. This actually saves us a lot of effort and wil help us get to the MVP state quicker.

Vendoring a package or updating a vendored package had never been troublesome, till I tried to vendor mgmt. I'll do what it takes to get mgmt vendored, but vendoring itself will not be removed.

**Comment by kshlm** [comment] 2017-02-28 08:31
(closed it by accident)

**Comment by purpleidea** [comment] 2017-02-28 17:33
> Vendoring is staying, and will not be removed. Period.

Doesn't leave much room for discussion, does it?

**Comment by prashanthpai** [comment] 2017-03-01 06:27
I have come across few projects that recommend to not use their master branch and rather use a tagged stable release. Without vendoring, we'll have to come up with our own vendoring like solution (for example [git submodules](https://groups.google.com/forum/#!topic/go-package-management/KR2zrSIsRho)) to depend on stable releases of dependencies. One thing we can all agree on is that we need a system that allows us to pin dependencies to some stable version other than master branch. Without this system in place, IMHO, developer productivity will take a hit. My 2 cents.

**Comment by purpleidea** [comment] 2017-03-01 06:51
@prashanthpai Some large and complex projects don't have a stable git master, which means we should vendor the minimum required (etcd is one example). And even in this case, we only vendor the minimum: https://github.com/purpleidea/mgmt/tree/master/vendor We only vendor the etcd main repo, and two grpc deps. Everything else is basically pretty stable and this hasn't caused us an issue in about a year.

One good example of this method working in practice. A number of months ago, our builds started breaking (we detect this quickly because we build routinely in cron as well as on new PR's) and it was easy to figure out what broke-- one small thing, and it was patched right away: https://github.com/purpleidea/mgmt/commit/ab73261fd4e98cf7ecb08066ad228a8f559ba16a

Had we wanted to move all the different vendored components, we'd have to have solved an !N (n-factorial) combinatorial problem to get a working solution.

There are some good presentations online about this method, and I can dig some up if you'd like. Google's presentations about their monorepo might be a good place to look. There was a good one from 2011 or 2012 or something, but I can't find it atm.

**Comment by prashanthpai** [comment] 2017-03-01 09:01
>  And even in this case, we only vendor the minimum

How do you converge on what this 'minimum' is ? And this 'minimum list of things to be vendored' can change overtime, needing adding or removal of dependencies. 

> Everything else is basically pretty stable and this hasn't caused us an issue in about a year.

You'll only know it's an issue only when something breaks ;) I guess you vendor only those three dependencies because you've seen them break or are likely to break often.

> and it was easy to figure out what broke-- one small thing, and it was patched right away

In this particular case, may be. But what if some bigger incompatibility came up for which the fix isn't straightforward ? You'll likely see the need to stick to the old version/commit which worked for you. While it's comforting to see being pro-actively compatible to the master branch of the dependency we depend on, it shouldn't be the top priority, especially during times where we want to get out a feature or release out and one of things blocking us will be an external dependency breakage. 

> There was a good one from 2011 or 2012 or something, but I can't find it atm.

Those were the days prior to go 1.6 which natively started to support `/vendor` directory.

glusterd2 repo in it's current state neither has code from dependencies in the repo  nor has [dependencies as git submodules](https://github.com/purpleidea/mgmt/blob/master/.gitmodules). This is [exactly how etcd repo](https://github.com/coreos/etcd/blob/master/glide.lock) also manages dependencies. There are projects who [actively use git submodule](https://github.com/kovetskiy/manul) for vendoring dependencies. glusterd2 isn't one of those projects yet. I'm not resisting the move to do selective vendoring using git submodules. But I personally don't see the need for it. And the supposed benefits (knowing when master branch of a dependency breaks glusterd2?) isn't convincing enough for me.

**Comment by purpleidea** [comment] 2017-03-01 09:35
> How do you converge on what this 'minimum' is ?

When you use other libraries and dependencies, you want to pick sane projects as much as possible. In general (there are a few exceptions like etcd) good projects with good maintainers try to keep their git master branch stable and functional. Assuming all the deps you use work this way, then you shouldn't need to vendor anything.

The only time you might vendor something is if you want to have a long term support branch, and at the time of that release you fork of a version branch for that. This is of course very expensive to maintain.

>  I guess you vendor only those three dependencies because you've seen them break or are likely to break often.

Actually the reason we vendor those three is because due to some nuances of grpc they require very specific version matching to work correctly. This is unfortunate, and I wish I had more time to dig into it and move them forward. That's sort of the point. If things seem to be working, and there are other more important priorities (there always are) then I'll never make that time until I'm on fire and then it's a harder fire to deal with.

> But what if some bigger incompatibility came up for which the fix isn't straightforward ? You'll likely see the need to stick to the old version/commit which worked for you.

Give me a concrete example of this, and I'll try and help you fix it. If we can't *then* we ask that upstream, and *then* we vendor as a last resort.

**Comment by prashanthpai** [comment] 2017-03-10 05:54
This seems relevant and interesting: https://github.com/golang/dep/wiki/Roadmap

**Comment by prashanthpai** [comment] 2017-05-18 09:59
Closing this issue because:

* We haven't so far stopped vendoring and in all likelihood won't do so in future.
* The cause and need for this issue i.e `mgmt` is already merged in master branch.

**Closed by prashanthpai** 2017-05-18 09:59 UTC
