### ISSUE TITLE
Add support to reload bricks on a different node

### ISSUE THREAD

**Issue by prashanthpai** [gluster/glusterd2#1104] opened 2018-07-31 05:33 UTC
The underlying storage used a s bricks may already be coming from a resilient distributed storage. Leveraging such storage capabilities should be possible which will allow glusterd2 to start up the same brick on another node.

This requires glusterd2 to loosely couple a brick to the node on which it is running.

**Comment by JohnStrunk** [comment] 2018-07-31 06:36
By "same brick on a different node", do you mean:
1) supporting the address of the node changing (i.e., nodeN at 1.2.3.4 restarts and is now at 5.6.7.8)?
or
2) taking a brick currently on nodeN and moving it (by re-attaching its storage) to nodeM (another node in the same gluster cluster)?

Currently, 1 is needed, but I don't see a significant use case for 2.

**Comment by aravindavk** [comment] 2018-11-28 07:47
Duplicate of https://github.com/gluster/glusterd2/issues/356

If brick can be mounted on other node, IP/hostname needs to be changed.

**Closed by aravindavk** 2018-11-28 07:47 UTC
Labels: FW: Volume Management, GCS-Stretch, feature
