### ISSUE TITLE
Implement volume shrink (remove brick)

### ISSUE THREAD

**Issue by prashanthpai** [gluster/glusterd2#319] opened 2017-06-12 09:59 UTC
Similar to volume expand API, this issue will track implementation of volume shrink (remove brick)

**Comment by atinmu** [comment] 2017-06-12 10:05
@purpleidea Can you please start working on this issue?

**Comment by purpleidea** [comment] 2017-06-12 10:07
@atinmu I really can't, sorry. I have no idea how this system works, and from our meetings the entire point of recommending the resource model was to avoid difficult problems like this one. Also I'm working on the disk provisioning stuff.

**Comment by atinmu** [comment] 2017-06-12 10:19
@purpleidea I do understand that you are working on disk provisioning stuffs and it'd be really great if you can point me out to the github issue link for the reference. FWIW, we'd really need additional help from you on the GD2 front as well to implement the APIs and other stuffs.

**Comment by purpleidea** [comment] 2017-06-12 10:20
@atinmu Happy to discuss, but the place is either in a meeting or on IRC, not here in a bug tracker.

**Comment by atinmu** [comment] 2017-11-28 12:48
Duplicate of #426

**Closed by atinmu** 2017-11-28 12:48 UTC
Labels: feature, FW: Volume Management, priority: high
