### ISSUE TITLE
node grouping option 

### ISSUE THREAD

**Issue by amarts** [gluster/glusterd2#416] opened 2017-11-13 12:21 UTC
## Problem Statement

There is no awareness to glusterd about where each node is, and there are no grouping of these nodes. One of the major usecase of grouping few nodes into different groups is rack awareness for the config layer. Also it can be extended to group them as different group of machines with different warranty expiry dates etc.

### Why do we need it?

Rack awareness, mainly because a true high availability in a local cluster be achieved when you can place your data on different racks, and not in adjacent machines.
Warranty period so that you can avoid sudden collapse of storage in one (or few) set of replica pairs. 

### What improvements can be immediately done?

* Provide option to `--group <group_name>` during `peer probe $peer`
* Provide an option to edit 'peer' details, where existing `group` can be changed. (There can be more properties for a given peer, IP/hostname being few of them).

**Comment by atinmu** [comment] 2017-11-13 13:38
IMO, we'd need check how heketi has handled this so far and have the respective APIs defined in glusterd2.

**Comment by prashanthpai** [comment] 2017-11-14 05:41
> Provide option to --group <group_name> during peer probe $peer

We had planned this - ability to set custom key/value pairs (metadata) for peers. The higher layers (dynamic provisioning bits) can set and interpret them in whatever way they would like. 

> Provide an option to edit 'peer' details, where existing group can be changed. (There can be more properties for a given peer, IP/hostname being few of them).

This is also planned. Phase 1 to get this done was to use `UUID` to represent bricks internally (unilke gd1 ehere it was `host:path`). So when the IP of a peer changes, we just have to change the peer list. That change has been completed.

**Comment by aravindavk** [comment] 2017-11-14 06:04
+1

We also need to tag/group the IPs of a peer, so that we can specify a IP which will be used only for Internal traffic, management traffic and client traffic etc. (Currently we are accepting hostname/IP as list)

**Comment by atinmu** [comment] 2017-11-30 11:31
## Checklist
- [ ] ReST APIs availibility in wiki
- [ ] CLI commands
- [ ] Sufficient logging
- [ ] Availibility of metrics data if applicable
- [ ] Xlator options table upto date?
- [ ] Test cases & test coverage of the functionality

**Comment by rishubhjain** [comment] 2018-01-29 10:41
@atinmu The grouping of nodes(for stack awareness) in heketi is done via mentioning the zone they(node) belong to  which is done when node is added (Please refer to https://github.com/heketi/heketi/blob/master/doc/api/api.md#add-node).
We can introduce similar concept in GD2 by requiring user to input the zone/group (whichever name is appropriate) while attaching peer.
This will be required by https://github.com/gluster/glusterd2/issues/466 as well.

**Comment by prashanthpai** [comment] 2018-01-29 11:29
> @aravindavk @prashanthpai Please suggest how can we introduce this concept in GD2

This is already considered at https://github.com/gluster/glusterd2/issues/482

**Comment by rishubhjain** [comment] 2018-02-05 07:10
@prashanthpai @aravindavk @amarts https://github.com/gluster/glusterd2/pull/549 addresses points mentioned in this issue. I will update the wiki to document these changes.

**Comment by rishubhjain** [comment] 2018-03-09 09:22
@prashanthpai During peer add the new peer is added with its group details, but the existing peer doesn't have  a default group. I would like some suggestions on what should be the default group assigned to peer.

**Comment by rishubhjain** [comment] 2018-03-09 09:31
As per discussion with @aravindavk, We can introduce another api with URL "/peers/MetaData" via which one can set or update group of a particular peer.

**Comment by rishubhjain** [comment] 2018-05-30 02:33
@atinmu Rest API is in but CLI commands are yet to be worked upon, will do it right away.

**Comment by prashanthpai** [comment] 2018-05-30 02:44
> @atinmu Rest API is in but CLI commands are yet to be worked upon, will do it right away.

This issue is largely a duplicate of https://github.com/gluster/glusterd2/issues/482
`Group` is one such metadata key. Please check if metadata and `zone` can be set from CLI during peer add. For general purposes, `group` and `zone` are the same.

**Comment by aravindavk** [comment] 2018-10-17 05:38
Based on the comment https://github.com/gluster/glusterd2/issues/416#issuecomment-393012807 this can be handled by setting zone or `peer.Metadata`. Closing this issue. Please reopen if the issue is not yet addressed.

**Closed by aravindavk** 2018-10-17 05:38 UTC
Labels: FW: Cluster Management, GCS/1.0-Blocker, priority: medium
