### ISSUE TITLE
Enhance brick representation and removal for distributed volumes

### ISSUE THREAD

**Issue by sunilheggodu** [gluster/glusterd2#516] opened 2018-01-04 06:17 UTC
GD1 doesn't differentiate the brick distribution set for "Distributed-Disperse/Replicate" volume type which makes its removal tedious.

For "Distributed-Disperse/Replicate" volume type options to remove a distribution set instead of brick remove would help.

**Comment by aravindavk** [comment] 2018-10-17 05:45
Gd2 groups the bricks based on sub volume it belongs to. It is easy to identify a brick which belongs to replicate/disperse subvolume. Closing this issue. Please reopen if the issue is not fixed.

**Closed by aravindavk** 2018-10-17 05:45 UTC
Labels: feature, priority: low
