### ISSUE TITLE
After enabling brick mux, i don't see the option brick-multiplex in volume info

### ISSUE THREAD

**Issue by Shrivaibavi** [gluster/glusterd2#1400] opened 2018-12-13 09:51 UTC
### Observed behavior
```
[root@dhcp35-30 ~]# glustercli volume info

Volume Name: abc
Type: Replicate
Volume ID: e42c6604-6cf7-4aac-bd5e-dfe0cd674d4f
State: Started
Transport-type: tcp
Options:
Number of Bricks: 3
Brick1: 10.70.35.30:/bricks/brick0/abc1
Brick2: 10.70.35.106:/bricks/brick0/abc2
Brick3: 10.70.35.240:/bricks/brick0/abc3

Volume Name: dif
Type: Replicate
Volume ID: dd797f61-0c20-4894-8447-9b734e21f63b
State: Started
Transport-type: tcp
Options:
Number of Bricks: 3
Brick1: 10.70.35.30:/bricks/brick0/dif
Brick2: 10.70.35.106:/bricks/brick1/dif
Brick3: 10.70.35.240:/bricks/brick2/dif
```
I see the volume option is empty.
### Expected/desired behavior
I see the volume option "brick-multiplex" : enabled in gd1 but not in gd2.
```
Volume Name: check3_8
Type: Replicate
Volume ID: c0b75345-49ad-4d51-a5e5-d71e65c814f8
Status: Started
Snapshot Count: 0
Number of Bricks: 1 x 3 = 3
Transport-type: tcp
Bricks:
Brick1: dhcp37-177.lab.eng.blr.redhat.com:/bricks/brick1/check_8
Brick2: dhcp37-149.lab.eng.blr.redhat.com:/bricks/brick1/check_8
Brick3: dhcp37-119.lab.eng.blr.redhat.com:/bricks/brick1/check_8
Options Reconfigured:
transport.address-family: inet
nfs.disable: on
performance.client-io-threads: off
cluster.brick-multiplex: enable
cluster.server-quorum-ratio: 99
cluster.max-bricks-per-process: 200
cluster.enable-shared-storage: enable
 
Volume Name: check3_9
Type: Replicate
Volume ID: 9e37597f-f6f4-459d-8a3b-7512e303a0e4
Status: Started
Snapshot Count: 0
Number of Bricks: 1 x 3 = 3
Transport-type: tcp
Bricks:
Brick1: dhcp37-177.lab.eng.blr.redhat.com:/bricks/brick1/check_9
Brick2: dhcp37-149.lab.eng.blr.redhat.com:/bricks/brick1/check_9
Brick3: dhcp37-119.lab.eng.blr.redhat.com:/bricks/brick1/check_9
Options Reconfigured:
transport.address-family: inet
nfs.disable: on
performance.client-io-threads: off
cluster.brick-multiplex: enable
cluster.server-quorum-ratio: 99
cluster.max-bricks-per-process: 200
cluster.enable-shared-storage: enable
```
### Information about the environment:

- Glusterd2 version used (e.g. v4.1.0 or master): 
glusterd version: v6.0-dev.69.git5f88917
git SHA: 5f88917
go version: go1.11.2
go OS/arch: linux/amd64

- Operating system used: 
- Glusterd2 compiled from sources, as a package (rpm/deb), or container: 
- Using External ETCD: (yes/no, if yes ETCD version):
- If container, which container image: 
- Using kubernetes, openshift, or direct install: 
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: 

### Other useful information

- glusterd2 config files from all nodes (default /etc/glusterd2/glusterd2.toml)
- glusterd2 log files from all nodes (default /var/log/glusterd2/glusterd2.log)
- ETCD configuration
- Contents of `uuid.toml` from all nodes (default /var/lib/glusterd2/uuid.toml)
- Output of `statedump` from any one of the node

### Useful commands

- To get glusterd2 version
    ```
    glusterd2 --version
    ```
- To get ETCD version
    ```
    etcd --version
    ```
- To get output of statedump
    ```
    curl http://glusterd2-IP:glusterd2-Port/statedump
    ```

**Comment by atinmu** [comment] 2018-12-13 09:53
It will not be shown in volume info given it’s a cluster wide global option. This is a(correct) change in behaviour if you’re doing a GD1 vs GD2 comparison.

**Comment by Shrivaibavi** [comment] 2018-12-13 12:07
@atinmu If it is not given in volume info, then what is the glustercli command to check cluster wide global option ?

**Comment by atinmu** [comment] 2018-12-13 15:47
Duplicate of #1401

**Closed by atinmu** 2018-12-13 15:47 UTC
