### ISSUE TITLE
Volume start failing with REST-API

### ISSUE THREAD

**Issue by rmadaka** [gluster/glusterd2#1067] opened 2018-07-25 13:43 UTC
Volume start failing with REST-API, 

curl -X POST http://10.70.35.33:24007/v1/volumes/rep1/start
{"errors":[{"code":1,"message":"EOF"}]}

Logs:
time="2018-07-25 19:13:18.856318" level=info msg="10.70.35.33 - - [25/Jul/2018:19:13:18 +0530] \"POST /v1/volumes/rep1/start HTTP/1.1\" 400 40" reqid=ec27fc92-1970-4378-987d-2cd8c79f6fa6

**Comment by prashanthpai** [comment] 2018-07-25 14:13
Duplicate of https://github.com/gluster/glusterd2/issues/1065

**Closed by prashanthpai** 2018-07-25 14:13 UTC
Labels: duplicate
