### ISSUE TITLE
Using rest-api volume "capacity, used and free"  sizes showing it as Zero for volume status on gcs setup

### ISSUE THREAD

**Issue by rmadaka** [gluster/glusterd2#1287] opened 2018-10-16 13:18 UTC
### Observed behavior
check volume status for auto-provisioned volume using rest-api on gcs setup. Volume capacity, used and free size showing it as ZERO.
```curl -X GET http://<IP>:24007/v1/volumes/pvc-a0b36d6fd14211e8/status
``` 
Output:

{
"info":{
"id":"81353a98-52d7-480e-ae0e-452b6d99e055",
"name":"pvc-a0b36d6fd14211e8",
"type":"Replicate",
"transport":"tcp",
"distribute-count":1,
"replica-count":3,
"options":{
},
"state":"Started",
"subvols":[
{
"name":"pvc-a0b36d6fd14211e8-replicate-0",
"type":"Replicate",
"bricks":[
{
"id":"e412d21f-788e-4b29-81c9-0f1aa8e2fda5",
"path":"/var/run/glusterd2/bricks/pvc-a0b36d6fd14211e8/subvol1/brick1/brick",
"volume-id":"81353a98-52d7-480e-ae0e-452b6d99e055",
"volume-name":"pvc-a0b36d6fd14211e8",
"peer-id":"19d8f8c0-642e-46fb-a049-aa83193c3b3e",
"host":"gluster-kube2-0.glusterd2.gcs",
"type":"Brick"
},
{
"id":"64639e1f-1933-4306-8e40-87a9034cfc60",
"path":"/var/run/glusterd2/bricks/pvc-a0b36d6fd14211e8/subvol1/brick2/brick",
"volume-id":"81353a98-52d7-480e-ae0e-452b6d99e055",
"volume-name":"pvc-a0b36d6fd14211e8",
"peer-id":"49be89c0-8e1e-40dc-a587-28974529c4db",
"host":"gluster-kube1-0.glusterd2.gcs",
"type":"Brick"
},
{
"id":"6fe370cb-7e9d-4451-b1e6-4b4e96306a96",
"path":"/var/run/glusterd2/bricks/pvc-a0b36d6fd14211e8/subvol1/brick3/brick",
"volume-id":"81353a98-52d7-480e-ae0e-452b6d99e055",
"volume-name":"pvc-a0b36d6fd14211e8",
"peer-id":"d3a07292-8298-4d67-bf3f-5fe6ed819a0d",
"host":"gluster-kube3-0.glusterd2.gcs",
"type":"Brick"
}
],
"replica-count":3,
"arbiter-count":0,
"disperse-count":0
}
],
"metadata":{
"GlusterFS-CSI":"gluster.org/glusterfs-csi"
},
"snap-list":[
]
},
"online":true,
"size":{
"capacity":0,
"used":0,
"free":0
}
}

### Expected/desired behavior

Volume capacity should as pvc size, used size should show according to how much data written and free size should show according to how much space left on volume.

### Details on how to reproduce (minimal and precise)

1) Create a pvc from kubernetes master node.
2) PVC should be in bound state
3) Then login to GD2 pod
4) check the volume status using rest-api.
5) In "size" filed "capacity", "used" and "free" sizes showing it as ZERO.

### Information about the environment:

- Glusterd2 version used (e.g. v4.1.0 or master): v4.1.0-202.gitea0c111
- Operating system used: centos 7.5
- Glusterd2 compiled from sources, as a package (rpm/deb), or container: contianer
- Using External ETCD: (yes/no, if yes ETCD version): yes
- If container, which container image: docker.io/gluster/glusterd2-nightly:20180920
- Using kubernetes, openshift, or direct install: kubernetes
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: inside

### Other useful information

- glusterd2 config files from all nodes (default /etc/glusterd2/glusterd2.toml)
- glusterd2 log files from all nodes (default /var/log/glusterd2/glusterd2.log)
- ETCD configuration
- Contents of `uuid.toml` from all nodes (default /var/lib/glusterd2/uuid.toml)
- Output of `statedump` from any one of the node

### Useful commands

- To get glusterd2 version
    ```
    glusterd2 --version
    ```
- To get ETCD version
    ```
    etcd --version
    ```
- To get output of statedump
    ```
    curl http://glusterd2-IP:glusterd2-Port/statedump
    ```

**Comment by aravindavk** [comment] 2018-10-17 08:49
I logged in to the setup and checked the generated volfile in `/var/log/glusterd2/glusterfs/bricks`

```
grep "export-statfs-size" *
var-run-glusterd2-bricks-pvc-4e8b4fd7d1d911e8-subvol1-brick3-brick.log:  4:     option export-statfs-size off
var-run-glusterd2-bricks-pvc-8df305c3d1d911e8-subvol1-brick3-brick.log:  4:     option export-statfs-size off
var-run-glusterd2-bricks-pvc-900a0070d1d811e8-subvol1-brick3-brick.log:  5:     option export-statfs-size off
```

I am seeing the option value as `off`, due to this bricks will not export their `statvfs` details, `df` on mount will get Volume size as zero.

The Patch to fix the issue is merged in glusterfs a month ago(https://review.gluster.org/c/glusterfs/+/21192).

Are we using nightly build of of glusterfs or release branch(5.0) in gcs?

**Comment by Madhu-1** [comment] 2018-10-17 09:08
@kshlm ^^

**Comment by aravindavk** [comment] 2018-10-17 09:09
I see following version of gluster installed in the gcs setup

```
rpm -qa | grep gluster                                                                                                        
glusterfs-libs-6dev-0.3.git76cb1e7.el7.x86_64
glusterfs-6dev-0.3.git76cb1e7.el7.x86_64
glusterfs-cli-6dev-0.3.git76cb1e7.el7.x86_64
glusterd2-4.1.0-202.gitea0c111.el7.x86_64
glusterfs-client-xlators-6dev-0.3.git76cb1e7.el7.x86_64
glusterfs-api-6dev-0.3.git76cb1e7.el7.x86_64
glusterfs-fuse-6dev-0.3.git76cb1e7.el7.x86_64
glusterfs-server-6dev-0.3.git76cb1e7.el7.x86_64
```

These rpms doesn't have the fix I mentioned(built on 2018-09-17).
Updating to the later version will fix the issue

In glusterfs nightly repo, latest version is available.(http://artifacts.ci.centos.org/gluster/nightly/master/7/x86_64/)

```
glusterfs-server-6dev-0.3.git76cb1e7.el7.x86_64.rpm	2018-09-17 00:56	1.5M	 
glusterfs-server-6dev-0.31.gitb139bc5.el7.x86_64.rpm	2018-09-21 01:00	1.5M	 
glusterfs-server-6dev-0.38.git9d8f5a3.el7.x86_64.rpm	2018-09-22 01:02	1.5M	 
glusterfs-server-6dev-0.42.gitb7732b9.el7.x86_64.rpm	2018-09-24 01:01	1.5M	 
glusterfs-server-6dev-0.47.git607b917.el7.x86_64.rpm	2018-09-25 00:55	1.5M	 
glusterfs-server-6dev-0.57.git65aed10.el7.x86_64.rpm	2018-09-26 01:01	1.5M	 
glusterfs-server-6dev-0.62.gitf1e9b87.el7.x86_64.rpm	2018-09-27 01:01	1.5M	 
glusterfs-server-6dev-0.66.git7cf6688.el7.x86_64.rpm	2018-09-29 00:58	1.5M	 
glusterfs-server-6dev-0.67.gitd00a2a1.el7.x86_64.rpm	2018-10-01 00:59	1.5M	 
glusterfs-server-6dev-0.78.gitfa091f0.el7.x86_64.rpm	2018-10-03 01:07	1.5M	 
glusterfs-server-6dev-0.80.git0153fcf.el7.x86_64.rpm	2018-10-04 00:57	1.5M	 
glusterfs-server-6dev-0.87.git3be7116.el7.x86_64.rpm	2018-10-05 01:07	1.5M	 
glusterfs-server-6dev-0.91.git76bd93c.el7.x86_64.rpm	2018-10-08 00:58	1.5M	 
glusterfs-server-6dev-0.99.gitb5f75e3.el7.x86_64.rpm	2018-10-09 01:07	1.5M	 
glusterfs-server-6dev-0.104.git3fa73bf.el7.x86_64.rpm	2018-10-10 00:58	1.5M	 
glusterfs-server-6dev-0.114.git27d3d48.el7.x86_64.rpm	2018-10-11 00:58	1.5M	 
glusterfs-server-6dev-0.117.git23e96fd.el7.x86_64.rpm	2018-10-12 01:07	1.5M	 
glusterfs-server-6dev-0.130.gitc962e2c.el7.x86_64.rpm	2018-10-15 00:58	1.5M	 
glusterfs-server-6dev-0.131.git76cc1ea.el7.x86_64.rpm	2018-10-16 01:07	1.5M	 
glusterfs-server-6dev-0.145.git573253d.el7.x86_64.rpm	2018-10-17 01:07	1.5M
```

**Comment by Madhu-1** [comment] 2018-10-25 09:48
@aravindavk doing testing once its done, I will update gd2 container to latest

**Comment by Madhu-1** [comment] 2018-10-25 10:18
Fixed by https://github.com/gluster/gcs/pull/45

**Comment by atinmu** [comment] 2018-10-25 11:35
Requires gluster/gcs#45

**Comment by JohnStrunk** [comment] 2018-10-25 18:55
Fix is now merged in gcs.

**Closed by JohnStrunk** 2018-10-25 18:55 UTC
Labels: FW: Volume Management, GCS/0.2, GCS/1.0-Blocker, in progress, priority: high
