### ISSUE TITLE
Replace node (move node to a different cluster)

### ISSUE THREAD

**Issue by prashanthpai** [gluster/glusterd2#277] opened 2017-02-28 07:23 UTC
This was a usecase from the containers team (kubernetes + gluster)

**Comment by atinmu** [comment] 2017-11-07 05:48
@prashanthpai Could you elaborate further on the use case more?

**Comment by atinmu** [comment] 2017-11-30 11:32
## Checklist
- [ ] ReST APIs availibility in wiki
- [ ] CLI commands
- [ ] Sufficient logging
- [ ] Availibility of metrics data if applicable
- [ ] Xlator options table upto date?
- [ ] Test cases & test coverage of the functionality

**Comment by amarts** [comment] 2018-04-17 17:57
Need more details here please. In the meantime, I am updating #472

**Comment by aravindavk** [comment] 2018-05-31 09:54
Closing this bug as duplicate of #472 

#472 covers all the combination of Replace brick/Peer

**Closed by aravindavk** 2018-05-31 09:54 UTC
Labels: FW: Cluster Management, FW: Volume Management, priority: medium
