### ISSUE TITLE
PV claim should succeed when quorum of nodes are up.

### ISSUE THREAD

**Issue by atinmu** [gluster/glusterd2#1358] opened 2018-12-01 09:27 UTC
Enhancement request in transaction engine:

GD2's transaction engine should be capable enough to serve PV claim requests when quorum of the gluster nodes are up in cluster. The idea is to bring in a replay mechanism in the engine so that any operations which are undone at nodes which haven't participated in the transaction can be attempted once it's back online.

**Comment by aravindavk** [comment] 2018-12-02 06:39
Duplicate of #1091

**Closed** 2018-12-02 07:46 UTC
