### ISSUE TITLE
Replicate volume created on single node without force

### ISSUE THREAD

**Issue by Akarsha-rai** [gluster/glusterd2#1466] opened 2019-01-07 09:37 UTC
### Observed behavior
Replicate volume created on single node without force
Change in gd1 & gd2 behaviour

### Expected/desired behavior
Replicate volume created on single node should throw warning message saying to use force flag

### Details on how to reproduce (minimal and precise)
Create a replica volume on single node

### Information about the environment:

- Glusterd2 version used (e.g. v4.1.0 or master): 
```
glusterd version: v6.0-dev.97.gita6fc33c
git SHA: a6fc33c
go version: go1.11.2
go OS/arch: linux/amd64
```

**Comment by aravindavk** [comment] 2019-01-08 13:04
Duplicate of https://github.com/gluster/glusterd2/issues/1184

**Closed by aravindavk** 2019-01-08 13:04 UTC
