### ISSUE TITLE
Glusterd2 consuming huge amount of memory when a brick is down

### ISSUE THREAD

**Issue by rafikc30** [gluster/glusterd2#1321] opened 2018-11-08 14:29 UTC
### Observed behavior

glusterd2 process consumes 82% of memory.

```
 PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                  
24616 root      20   0 15.179g 3.054g   4552 S   1.7 82.5   3:08.14 glusterd2                                                                                                
  783 ovirtag+  20   0  547296   7800   3496 S   0.7  0.2  43:59.27 python                                                                                                   
  436 root      20   0       0      0      0 S   0.3  0.0   2:17.23 xfsaild/dm-0                                                                                             
24870 root      20   0 1185580   7208    168 S   0.3  0.2   0:04.67 glusterfsd                                                                                               
25003 root      20   0  626548   8060   1008 S   0.3  0.2   0:37.50 glusterfs  

```

### Expected/desired behavior

Memory should not increase to 82%

### Details on how to reproduce (minimal and precise)

1) Start glusterd2
2) Create a replica volume
3) Bring down one brick
4) Observe the memory usage

### Information about the environment:

- Glusterd2 version used (e.g. v4.1.0 or master): master
- Operating system used: fedora
- Glusterd2 compiled from sources, as a package (rpm/deb), or container: source install
- Using External ETCD: (yes/no, if yes ETCD version):
- If container, which container image: 
- Using kubernetes, openshift, or direct install: 
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside:

**Comment by harigowtham** [comment] 2018-11-26 15:18
Hi, 

The leak is found to be in ReadFullRecord() of the pkg/sunrpc/record.go

The place where we do allocations is:
record := bytes.NewBuffer(make([]byte, 0, maxRecordSize))

-Hari.

**Comment by aravindavk** [comment] 2018-11-27 07:45
> The leak is found to be in ReadFullRecord() of the pkg/sunrpc/record.go

> The place where we do allocations is:
> record := bytes.NewBuffer(make([]byte, 0, maxRecordSize))

Any suggestion to fix/prevent the issue?

**Comment by harigowtham** [comment] 2018-12-04 09:05
The below code is infinitely called to listen to the sunrpc calls.  

func (s *SunRPC) acceptLoop(stopCh chan struct{}, l net.Listener, wg *sync.WaitGroup) {
        defer wg.Done()

        var ltype string
        switch l.(type) {
        case *net.UnixListener:
                ltype = "unix"
        default:
                ltype = "tcp"
        }
        logger := log.WithFields(log.Fields{
                "server":    "sunrpc",
                "transport": ltype})
        logger.WithField("address", l.Addr().String()).Info("started server")

        sessions := make([]rpc.ServerCodec, 50)
        for {
                select {
                case <-stopCh:
                        logger.Debug("stopped accepting new connections")
                        logger.Debug("closing client connections")
                        for _, c := range sessions {
                                if c != nil {
                                        c.Close()
                                }
                        }
                        return
                default:
                }

                conn, err := l.Accept()
                if err != nil {
                        continue
                }

                logger.WithField("address", conn.RemoteAddr().String()).Info("client connected")
                clientCount.Add(1)
                clientsList.Lock()
                clientsList.c[conn] = struct{}{}
                clientsList.Unlock()
                // Create one rpc.Server instance per client. This is a
                // workaround to allow RPC programs to access underlying
                // net.Conn object and has minimal overhead. See:
                // https://groups.google.com/d/msg/golang-nuts/Gt-1ikXovCA/aK8r9MAftDQJ
                server := rpc.NewServer()

                for _, p := range programsList {
                        if v, ok := p.(Conn); ok {
                                v.SetConn(conn)
                        }
                        // server.Register() throws some benign but very
                        // annoying log messages complaining about signatures
                        // of methods. These logs can be safely ignored. See:
                        // https://github.com/golang/go/issues/19957
                        if err := server.Register(p); err != nil {
                                panic(fmt.Sprintf("rpc.Register failed: %s", err.Error()))
                        }
                }

                session := sunrpc.NewServerCodec(conn, s.notifyCloseCh)
                go server.ServeCodec(session)
                sessions = append(sessions, session)
        }
}

The NewServerCodec is the one which calls the ReadFullRecord where the leak happens.

The leak has been observed from this change 2dd8c0daf01326ea144103b4a9af448809800c9b which has a fixme saying that the goroutine leaks. 

On earlier inspection, It is found that it is not related to the goroutine not releasing memory (verified it with the debug.FreeOSMemory which is supposed to force free it but doesn't as the memory is still being held by the program) 

As the reference has been kept alive until the RPC is stopped, the memory keeps growing. 
This loop has to be run infinitely as the listening has to happen until the GD2 process runs.

To handle this we need to implement a connection reset which will quit the infinite loop and give back the memory to the OS and the start the listening again from the beginning. The reset should be called after a few connect failures, but the connect failures are relayed back to the server. So we aren't aware when we can restart the RPC connection. Once we get a clear idea about this we can work on that.

The workaround to minimize the leak is to reset the patch https://github.com/prashanthpai/sunrpc/commit/eb3316e05bea4bdbef3c8d12d1609e67dfd8223a 
This change in sunrpc to cap the limit made the size allocated a bigger value and the leak got worse.
If we reset it the leak is being reduced well.

**Comment by Madhu-1** [comment] 2018-12-05 05:52
`rpc source="[server.go:155:sunrpc.(*SunRPC).acceptLoop]" transport=tcp
time="2018-12-05 05:47:45.827334" level=info msg="client disconnected" address="10.233.66.5:962" server=sunrpc source="[server.go:109:sunrpc.(*SunRPC).pruneConn]"
time="2018-12-05 05:47:51.008626" level=info msg="client connected" address="10.233.66.5:988" server=sunrpc source="[server.go:155:sunrpc.(*SunRPC).acceptLoop]" transport=tcp
time="2018-12-05 05:47:51.010961" level=info msg="client disconnected" address="10.233.66.5:988" server=sunrpc source="[server.go:109:sunrpc.(*SunRPC).pruneConn]"
time="2018-12-05 05:47:56.186907" level=info msg="client connected" address="10.233.66.5:983" server=sunrpc source="[server.go:155:sunrpc.(*SunRPC).acceptLoop]" transport=tcp
time="2018-12-05 05:47:56.189088" level=info msg="client disconnected" address="10.233.66.5:983" server=sunrpc source="[server.go:109:sunrpc.(*SunRPC).pruneConn]"
`
even when PVC is created am seeing a memory leak issue, 
@aravindavk can you add more info regarding the cause of memory leak due to `gluster-exporter`

**Comment by aravindavk** [comment] 2018-12-05 06:08
> @aravindavk can you add more info regarding the cause of memory leak due to gluster-exporter

Looks like while collecting heal info, `glfsheal` command mounts the volume and gets the heal info. Since this runs in regular interval, glusterd2 memory consumption is growing.

**Comment by Madhu-1** [comment] 2018-12-05 08:10
>Looks like while collecting heal info, glfsheal command mounts the volume and gets the heal info. Since this runs in regular interval, glusterd2 memory consumption is growing.?

if we have more  volumes in the gd2 cluster this will cause the issue

**Comment by aravindavk** [comment] 2018-12-05 09:22
Try adding `conn.Close()` in `func (s *SunRPC) pruneConn()` (`$SRC/glusterd2/servers/sunrpc/server.go`, After Line 108)

**Comment by harigowtham** [comment] 2018-12-05 09:57
The memory still keeps growing

**Closed** 2018-12-07 03:37 UTC
Labels: GCS/0.4, GCS/1.0-Blocker, bug, priority: high
