### ISSUE TITLE
adding peer followed by removal of same peer cause panic

### ISSUE THREAD

**Issue by oshankkumar** [gluster/glusterd2#1092] opened 2018-07-30 10:21 UTC
# Command Executed
[okumar@localhost glusterd2]$ ./build/glustercli --endpoints=http://192.168.122.42:24007 peer list
+--------------------------------------+--------------+-----------------------+-----------------------+--------+------+
|                  ID                  |     NAME     |   CLIENT ADDRESSES    |    PEER ADDRESSES     | ONLINE | PID  |
+--------------------------------------+--------------+-----------------------+-----------------------+--------+------+
| 2f0bfdac-fceb-459a-8939-689da17de77e | gd21.example | 127.0.0.1:24007       | 192.168.122.6:24008   | yes    | 2156 |
|                                      |              | 192.168.122.6:24007   |                       |        |      |
| 854e037e-da80-4ee0-82b8-9ecdb8fc13de | gd22.example | 127.0.0.1:24007       | 192.168.122.42:24008  | yes    | 2563 |
|                                      |              | 192.168.122.42:24007  |                       |        |      |
| a35e9c07-fc7c-45ac-a0a3-4e09869b30ca | gd20.example | 127.0.0.1:24007       | 192.168.122.253:24008 | yes    | 2586 |
|                                      |              | 192.168.122.253:24007 |                       |        |      |
+--------------------------------------+--------------+-----------------------+-----------------------+--------+------+
./build/glustercli --endpoints=http://192.168.122.42:24007 peer remove 2f0bfdac-fceb-459a-8939-689da17de77e
Peer remove success
[okumar@localhost glusterd2]$ ./build/glustercli --endpoints=http://192.168.122.42:24007 peer list
+--------------------------------------+--------------+-----------------------+-----------------------+--------+------+
|                  ID                  |     NAME     |   CLIENT ADDRESSES    |    PEER ADDRESSES     | ONLINE | PID  |
+--------------------------------------+--------------+-----------------------+-----------------------+--------+------+
| 854e037e-da80-4ee0-82b8-9ecdb8fc13de | gd22.example | 127.0.0.1:24007       | 192.168.122.42:24008  | yes    | 2563 |
|                                      |              | 192.168.122.42:24007  |                       |        |      |
| a35e9c07-fc7c-45ac-a0a3-4e09869b30ca | gd20.example | 127.0.0.1:24007       | 192.168.122.253:24008 | yes    | 2586 |
|                                      |              | 192.168.122.253:24007 |                       |        |      |
+--------------------------------------+--------------+-----------------------+-----------------------+--------+------+
./build/glustercli --endpoints=http://192.168.122.42:24007 peer add 192.168.122.6
Peer add failed

Error: Request failed with HTTP Status code 500
failed to send join cluster request

# LOGS
INFO[2018-07-30 06:13:25.031666] handling new incoming join cluster request    remotecluster=21e282a0-398b-4726-88ab-af32b79f0237 remotepeer=854e037e-da80-4ee0-82b8-9ecdb8fc13de source="[peer-rpc-svc.go:45:peers.(*PeerService).Join]"
DEBU[2018-07-30 06:13:25.032392] all checks passed, joining new cluster        remotecluster=21e282a0-398b-4726-88ab-af32b79f0237 remotepeer=854e037e-da80-4ee0-82b8-9ecdb8fc13de source="[peer-rpc-svc.go:68:peers.(*PeerService).Join]"
DEBU[2018-07-30 06:13:25.032635] destroying current store                      source="[peer-rpc-svc.go:158:peers.ReconfigureStore]"
panic: close of closed channel

goroutine 225 [running]:
github.com/gluster/glusterd2/glusterd2/events.stopLivenessWatcher()
	/root/go/src/github.com/gluster/glusterd2/glusterd2/events/liveness.go:77 +0x30
github.com/gluster/glusterd2/glusterd2/events.Stop(0xc4206ab8d0, 0x1)
	/root/go/src/github.com/gluster/glusterd2/glusterd2/events/events.go:51 +0x22
github.com/gluster/glusterd2/glusterd2/commands/peers.ReconfigureStore(0xc4209fbf80, 0x0, 0x0)
	/root/go/src/github.com/gluster/glusterd2/glusterd2/commands/peers/peer-rpc-svc.go:161 +0x8b
github.com/gluster/glusterd2/glusterd2/commands/peers.(*PeerService).Join(0xc4208eb528, 0x110ed80, 0xc4209c59b0, 0xc4209c5a10, 0x0, 0x0, 0x0)
	/root/go/src/github.com/gluster/glusterd2/glusterd2/commands/peers/peer-rpc-svc.go:83 +0x3b6
github.com/gluster/glusterd2/glusterd2/commands/peers._PeerService_Join_Handler(0xedb200, 0xc4208eb528, 0x110ed80, 0xc4209c59b0, 0xc42009f360, 0x0, 0x0, 0x0, 0xc4207b6dd8, 0xc420040e00)
	/root/go/src/github.com/gluster/glusterd2/glusterd2/commands/peers/peer-rpc.pb.go:209 +0x241
github.com/gluster/glusterd2/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc420154240, 0x1114f40, 0xc4208a0750, 0xc420120960, 0xc42088e420, 0x184f2a0, 0xc4209c5980, 0x0, 0x0)
	/root/go/src/github.com/gluster/glusterd2/vendor/google.golang.org/grpc/server.go:638 +0x8f3
github.com/gluster/glusterd2/vendor/google.golang.org/grpc.(*Server).handleStream(0xc420154240, 0x1114f40, 0xc4208a0750, 0xc420120960, 0xc4209c5980)
	/root/go/src/github.com/gluster/glusterd2/vendor/google.golang.org/grpc/server.go:796 +0x1052
github.com/gluster/glusterd2/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc420a06c20, 0xc420154240, 0x1114f40, 0xc4208a0750, 0xc420120960)
	/root/go/src/github.com/gluster/glusterd2/vendor/google.golang.org/grpc/server.go:449 +0x9f
created by github.com/gluster/glusterd2/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/root/go/src/github.com/gluster/glusterd2/vendor/google.golang.org/grpc/server.go:447 +0xa1

**Comment by prashanthpai** [comment] 2018-07-30 13:10
@oshankkumar Are you using external etcd ?

**Comment by prashanthpai** [comment] 2018-07-31 03:50
This issue may be a duplicate of https://github.com/gluster/glusterd2/issues/1012

**Closed** 2018-08-01 06:53 UTC
Labels: FW: Cluster Management, FW: Events, GCS-Blocker, bug, duplicate, priority: high
