### ISSUE TITLE
Bricks went down suddenly when in the middle of testing

### ISSUE THREAD

**Issue by Shrivaibavi** [gluster/glusterd2#1208] opened 2018-08-31 15:07 UTC
### Steps done
 ``` glustercli device add a800a499-6820-4c45-8d72-34da4491a2cf /dev/vdc
Device add successful

[root@dhcp35-30 ~]# glustercli device add a800a499-6820-4c45-8d72-34da4491a2cf /dev/vdd
Device add successful

[root@dhcp35-30 ~]# curl -X POST http://10.70.35.30:24007/v1/volumes --data @vol.json -H 'Content-Type: application/json'
{"id":"62e8afd2-4ef7-4526-adab-bb08ee8084be","name":"test01","type":"Distribute","transport":"tcp","distribute-count":1,"replica-count":1,"options":{},"state":"Created","subvols":[{"name":"test01-distribute-0","type":"Distribute","bricks":[{"id":"4c21fca9-3517-426b-ac7a-59f5ffb9bb75","path":"/var/run/glusterd2/bricks/test01/subvol1/brick1/brick","volume-id":"62e8afd2-4ef7-4526-adab-bb08ee8084be","volume-name":"test01","peer-id":"a800a499-6820-4c45-8d72-34da4491a2cf","host":"10.70.35.30","type":"Brick"}],"replica-count":1,"arbiter-count":0,"disperse-count":0}],"metadata":{},"snap-list":[]}

[root@dhcp35-30 ~]# glustercli volume list
+--------------------------------------+--------+------------+---------+-----------+--------+
|                  ID                  |  NAME  |    TYPE    |  STATE  | TRANSPORT | BRICKS |
+--------------------------------------+--------+------------+---------+-----------+--------+
| 62e8afd2-4ef7-4526-adab-bb08ee8084be | test01 | Distribute | Created | tcp       | 1      |
+--------------------------------------+--------+------------+---------+-----------+--------+

[root@dhcp35-30 ~]# glustercli volume start test01
Volume test01 started successfully

[root@dhcp35-30 ~]# glustercli volume info

Volume Name: test01
Type: Distribute
Volume ID: 62e8afd2-4ef7-4526-adab-bb08ee8084be
State: Started
Transport-type: tcp
Options:
Number of Bricks: 1
Brick1: 10.70.35.30:/var/run/glusterd2/bricks/test01/subvol1/brick1/brick

[root@dhcp35-30 ~]# glustercli snapshot create snap1 test01
snap1 Snapshot created successfully
Snapshot Volume ID:  92479b15-7923-4828-8b64-370ef14b73cf

[root@dhcp35-30 ~]# glustercli snapshot activate snap1
Snapshot snap1 activated successfully

[root@dhcp35-30 ~]# for i in {2..11}; do glustercli snapshot create snap$i test01; done
snap2 Snapshot created successfully
Snapshot Volume ID:  6f58a776-494c-4ccd-bdb3-7a464bf8479e
snap3 Snapshot created successfully
Snapshot Volume ID:  acfb52fe-5056-4299-95a2-8e88f5207d91
snap4 Snapshot created successfully
Snapshot Volume ID:  2307e56b-8c5a-4867-8ca4-01b3fbad4296
snap5 Snapshot created successfully
Snapshot Volume ID:  6fdd9cdb-e972-456d-9656-093f25221856
snap6 Snapshot created successfully
Snapshot Volume ID:  ad0f3153-9bf8-406f-a1f5-28d5cbc09b8e
snap7 Snapshot created successfully
Snapshot Volume ID:  b72f5b33-9e2e-4d37-b006-f7027c33c209
snap8 Snapshot created successfully
Snapshot Volume ID:  76a6b371-3a0d-442b-ace3-6d9eed44c730
snap9 Snapshot created successfully
Snapshot Volume ID:  1153b1e0-6911-4ab8-8d53-020fcd062c7f
snap10 Snapshot created successfully
Snapshot Volume ID:  121894eb-8940-4454-ae78-94adbb365a5e
snap11 Snapshot created successfully
Snapshot Volume ID:  10c4f143-13df-480e-88cf-65e8e2e5645c

[root@dhcp35-30 ~]# glustercli snapshot list
+--------+---------------+
|  NAME  | ORIGIN VOLUME |
+--------+---------------+
| snap1  | test01        |
+--------+               +
| snap10 |               |
+--------+               +
| snap11 |               |
+--------+               +
| snap2  |               |
+--------+               +
| snap3  |               |
+--------+               +
| snap4  |               |
+--------+               +
| snap5  |               |
+--------+               +
| snap6  |               |
+--------+               +
| snap7  |               |
+--------+               +
| snap8  |               |
+--------+               +
| snap9  |               |
+--------+---------------+

```
### Observed behavior

``` [root@dhcp35-30 ~]# glustercli volume stop test
Broadcast message from systemd-journald@dhcp35-30.lab.eng.blr.redhat.com (Fri 2018-08-31 19:34:21 IST):

var-run-glusterd2-bricks-test01-subvol1-brick1-brick[1632]: [2018-08-31 14:04:21.673805] M [MSGID: 113075] [posix-helpers.c:2153:posix_health_check_thread_proc] 0-test01-posix: health-check failed, going down


Broadcast message from systemd-journald@dhcp35-30.lab.eng.blr.redhat.com (Fri 2018-08-31 19:34:21 IST):

var-run-glusterd2-bricks-test01-subvol1-brick1-brick[1632]: [2018-08-31 14:04:21.673959] M [MSGID: 113075] [posix-helpers.c:2172:posix_health_check_thread_proc] 0-test01-posix: still alive! -> SIGTERM


Message from syslogd@localhost at Aug 31 19:34:21 ...
 var-run-glusterd2-bricks-test01-subvol1-brick1-brick[1632]:[2018-08-31 14:04:21.673805] M [MSGID: 113075] [posix-helpers.c:2153:posix_health_check_thread_proc] 0-test01-posix: health-check failed, going down

Message from syslogd@localhost at Aug 31 19:34:21 ...
 var-run-glusterd2-bricks-test01-subvol1-brick1-brick[1632]:[2018-08-31 14:04:21.673959] M [MSGID: 113075] [posix-helpers.c:2172:posix_health_check_thread_proc] 0-test01-posix: still alive! -> SIGTERM
^C

[root@dhcp35-30 ~]# glustercli volume status
Volume : test01
+--------------------------------------+-------------+-------------------------------------------------------+--------+------+-----+
|               BRICK ID               |    HOST     |                         PATH                          | ONLINE | PORT | PID |
+--------------------------------------+-------------+-------------------------------------------------------+--------+------+-----+
| 4c21fca9-3517-426b-ac7a-59f5ffb9bb75 | 10.70.35.30 | /var/run/glusterd2/bricks/test01/subvol1/brick1/brick | false  |    0 |   0 |
+--------------------------------------+-------------+-------------------------------------------------------+--------+------+-----+

[root@dhcp35-30 ~]# glustercli volume info

Volume Name: test01
Type: Distribute
Volume ID: 62e8afd2-4ef7-4526-adab-bb08ee8084be
State: Started
Transport-type: tcp
Options:
    features.barrier: disable
Number of Bricks: 1
Brick1: 10.70.35.30:/var/run/glusterd2/bricks/test01/subvol1/brick1/brick

[root@dhcp35-30 ~]# 
Broadcast message from systemd-journald@dhcp35-30.lab.eng.blr.redhat.com (Fri 2018-08-31 19:36:48 IST):

var-run-glusterd2-snaps-snap1-test01-subvol1-brick1-brick[1704]: [2018-08-31 14:06:48.874527] M [MSGID: 113075] [posix-helpers.c:2153:posix_health_check_thread_proc] 0-snap1-posix: health-check failed, going down


Broadcast message from systemd-journald@dhcp35-30.lab.eng.blr.redhat.com (Fri 2018-08-31 19:36:48 IST):

var-run-glusterd2-snaps-snap1-test01-subvol1-brick1-brick[1704]: [2018-08-31 14:06:48.874652] M [MSGID: 113075] [posix-helpers.c:2172:posix_health_check_thread_proc] 0-snap1-posix: still alive! -> SIGTERM


Message from syslogd@localhost at Aug 31 19:36:48 ...
 var-run-glusterd2-snaps-snap1-test01-subvol1-brick1-brick[1704]:[2018-08-31 14:06:48.874527] M [MSGID: 113075] [posix-helpers.c:2153:posix_health_check_thread_proc] 0-snap1-posix: health-check failed, going down

Message from syslogd@localhost at Aug 31 19:36:48 ...
 var-run-glusterd2-snaps-snap1-test01-subvol1-brick1-brick[1704]:[2018-08-31 14:06:48.874652] M [MSGID: 113075] [posix-helpers.c:2172:posix_health_check_thread_proc] 0-snap1-posix: still alive! -> SIGTERM
^C
```

### Information about the environment:

- glusterd version: v4.1.0-164.gite8ebe18
git SHA: e8ebe18
go version: go1.9.4
go OS/arch: linux/amd64
 
-  CentOS Linux release 7.4.1708 (Core)

- Glusterd2 compiled from sources, as a package (rpm/deb), or container: No

- Using External ETCD: (yes/no, if yes ETCD version): yes

- If container, which container image:  No

- Using kubernetes, openshift, or direct install:  No 
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: No

### Other useful information

- localstatedir = "/var/lib/glusterd2"
logdir = "/var/log/glusterd2"
logfile = "glusterd2.log"
loglevel = "INFO"
rundir = "/var/run/glusterd2"
defaultpeerport = "24008"
peeraddress = ":24008"
clientaddress = ":24007"
restauth = false
etcdendpoints = "http://10.70.35.173:2379"
noembed = true

- Contents of `uuid.toml` from all nodes (default /var/lib/glusterd2/uuid.toml)
cluster-id = "63b39a41-c5c8-4518-93ec-4667f987207e"
peer-id = "a800a499-6820-4c45-8d72-34da4491a2cf"

- Output of `statedump` from any one of the node
``` [root@dhcp35-30 ~]# curl http://10.70.35.30:24007/statedump
{
"cluster-id": "63b39a41-c5c8-4518-93ec-4667f987207e",
"cmdline": ["/usr/sbin/glusterd2","--config=/etc/glusterd2/glusterd2.toml"],
"config": {"cert-file": "", "clientaddress": ":24007", "config": "/etc/glusterd2/glusterd2.toml", "defaultpeerport": "24008", "etcd-client-ca-file": "", "etcd-client-cert-file": "", "etcd-client-key-file": "", "etcdcurls": [], "etcdendpoints": [], "etcdpurls": [], "hooksdir": "/var/lib/glusterd2/hooks", "jaeger-agent-endpoint": "", "jaeger-endpoint": "", "key-file": "", "localstatedir": "/var/lib/glusterd2", "logdir": "/var/log/glusterd2", "logfile": "glusterd2.log", "loglevel": "INFO", "noembed": false, "peeraddress": "10.70.35.30:24008", "pidfile": "/var/run/glusterd2/glusterd2.pid", "restauth": false, "rundir": "/var/run/glusterd2", "statedump": true, "version": false},
"file_descriptor_limit": 1024,
"http": {"client_errors": 1, "in_progress": 1, "server_errors": 1, "success": 24, "total_requests_received": 26},
"memstats": {"Alloc":16829920,"TotalAlloc":814367072,"Sys":51255544,"Lookups":39213,"Mallocs":2905670,"Frees":2863097,"HeapAlloc":16829920,"HeapSys":45711360,"HeapIdle":22077440,"HeapInuse":23633920,"HeapReleased":21487616,"HeapObjects":42573,"StackInuse":1015808,"StackSys":1015808,"MSpanInuse":277856,"MSpanSys":409600,"MCacheInuse":5208,"MCacheSys":16384,"BuckHashSys":1673296,"GCSys":1720320,"OtherSys":708776,"NextGC":33229360,"LastGC":1535727318203186763,"PauseTotalNs":35750269,"PauseNs":[964120,7227795,293102,169656,51650,58585,501573,227199,8076088,74719,134805,238387,194572,217229,209108,87035,163419,196771,192888,240210,154033,249884,209461,84786,221688,184196,185581,255291,171937,169259,140918,136528,142711,140415,202413,140310,81840,220588,193183,200032,133401,204384,203706,181766,119343,177338,144916,227257,205824,204386,116705,101463,235034,102947,149505,142167,147027,203115,106613,106636,96184,139126,91881,113889,137975,99660,131778,117016,126887,138576,174313,81299,102704,139899,120790,130808,136443,108160,143481,132922,282379,184765,135109,157400,108687,184089,163399,308145,147723,126352,217721,105528,178126,179182,184805,100736,218438,111907,156729,114848,239476,99798,191051,202608,175342,169260,195521,203887,159068,158270,202361,233708,162508,134285,209009,105695,157767,160272,433629,109397,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"PauseEnd":[1535718945551856001,1535718945719564113,1535718945966655274,1535718946227413256,1535718946254206348,1535718946281483845,1535718946309431486,1535718946337655133,1535718946372409574,1535718946403164444,1535718966465179845,1535719086518691846,1535719206539873241,1535719326607205202,1535719446641058191,1535719566707193569,1535719686742889582,1535719806778729593,1535719926784387787,1535720046789310065,1535720166795367793,1535720286800141331,1535720406806088838,1535720526812775486,1535720646840939149,1535720766861303735,1535720886869027288,1535721006877381615,1535721126886254932,1535721246896565489,1535721366906764248,1535721486915302523,1535721606923845633,1535721726933519962,1535721846940889902,1535721966950407581,1535722086960334329,1535722206968594628,1535722326977103329,1535722446984989186,1535722566993577901,1535722687001292546,1535722807009429589,1535722927017981896,1535723047027158658,1535723167035819220,1535723287040000472,1535723407051835903,1535723527059148252,1535723647068574063,1535723767077176092,1535723887085139338,1535724007094503053,1535724073588618739,1535724106533675149,1535724106686504434,1535724194614027283,1535724194768956797,1535724194876304619,1535724195025479305,1535724195127360246,1535724195284373230,1535724195325280193,1535724195429699303,1535724195496193877,1535724195545144957,1535724195588429200,1535724195700240128,1535724195771524820,1535724195813441504,1535724195919628953,1535724195962716415,1535724196040178125,1535724196089247400,1535724196198325622,1535724196243107008,1535724196317710125,1535724196364896055,1535724196409681152,1535724196527599501,1535724196600388218,1535724196649982934,1535724196704195925,1535724196770985960,1535724196869255932,1535724196939480035,1535724196986918374,1535724197045319445,1535724197087544186,1535724197216512350,1535724197290431227,1535724197343084843,1535724197394096343,1535724197445667715,1535724317521447612,1535724437539989362,1535724557620561957,1535724677640639222,1535724797657015736,1535724917675830513,1535725037720901814,1535725157728102511,1535725277736269532,1535725397741790540,1535725517809383019,1535725637840901509,1535725757869183412,1535725877896304967,1535725997913665508,1535726117941224408,1535726237972209771,1535726357995828581,1535726478009361145,1535726598041405838,1535726718071494805,1535726838098986738,1535726958110087388,1535727078140810929,1535727198176301409,1535727318203186763,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"NumGC":120,"NumForcedGC":0,"GCCPUFraction":0.000027534089648860036,"EnableGC":true,"DebugGC":false,"BySize":[{"Size":0,"Mallocs":0,"Frees":0},{"Size":8,"Mallocs":40044,"Frees":39348},{"Size":16,"Mallocs":546456,"Frees":532033},{"Size":32,"Mallocs":439844,"Frees":428569},{"Size":48,"Mallocs":459238,"Frees":453251},{"Size":64,"Mallocs":349361,"Frees":346374},{"Size":80,"Mallocs":58393,"Frees":58036},{"Size":96,"Mallocs":188306,"Frees":187126},{"Size":112,"Mallocs":74424,"Frees":73604},{"Size":128,"Mallocs":49147,"Frees":48904},{"Size":144,"Mallocs":8070,"Frees":7896},{"Size":160,"Mallocs":11221,"Frees":10870},{"Size":176,"Mallocs":68998,"Frees":68880},{"Size":192,"Mallocs":3985,"Frees":3946},{"Size":208,"Mallocs":47710,"Frees":47471},{"Size":224,"Mallocs":87350,"Frees":86436},{"Size":240,"Mallocs":29869,"Frees":29847},{"Size":256,"Mallocs":5431,"Frees":5331},{"Size":288,"Mallocs":32256,"Frees":32112},{"Size":320,"Mallocs":27600,"Frees":27495},{"Size":352,"Mallocs":5546,"Frees":5494},{"Size":384,"Mallocs":3846,"Frees":3505},{"Size":416,"Mallocs":1262,"Frees":1227},{"Size":448,"Mallocs":1145,"Frees":1104},{"Size":480,"Mallocs":1341,"Frees":1316},{"Size":512,"Mallocs":1740,"Frees":1692},{"Size":576,"Mallocs":15064,"Frees":15001},{"Size":640,"Mallocs":2414,"Frees":2363},{"Size":704,"Mallocs":2061,"Frees":2043},{"Size":768,"Mallocs":2514,"Frees":2503},{"Size":896,"Mallocs":4894,"Frees":4855},{"Size":1024,"Mallocs":6098,"Frees":5941},{"Size":1152,"Mallocs":8808,"Frees":8761},{"Size":1280,"Mallocs":4211,"Frees":4133},{"Size":1408,"Mallocs":4293,"Frees":4283},{"Size":1536,"Mallocs":4886,"Frees":4877},{"Size":1792,"Mallocs":10838,"Frees":10788},{"Size":2048,"Mallocs":9613,"Frees":9571},{"Size":2304,"Mallocs":9208,"Frees":8970},{"Size":2688,"Mallocs":11284,"Frees":11183},{"Size":3072,"Mallocs":11814,"Frees":11603},{"Size":3200,"Mallocs":3023,"Frees":3021},{"Size":3456,"Mallocs":5591,"Frees":5591},{"Size":4096,"Mallocs":17193,"Frees":17168},{"Size":4864,"Mallocs":15672,"Frees":15668},{"Size":5376,"Mallocs":10782,"Frees":10735},{"Size":6144,"Mallocs":13257,"Frees":12864},{"Size":6528,"Mallocs":2672,"Frees":2667},{"Size":6784,"Mallocs":1299,"Frees":1299},{"Size":6912,"Mallocs":658,"Frees":658},{"Size":8192,"Mallocs":6830,"Frees":6611},{"Size":9472,"Mallocs":7,"Frees":5},{"Size":9728,"Mallocs":17,"Frees":17},{"Size":10240,"Mallocs":2,"Frees":2},{"Size":10880,"Mallocs":5,"Frees":4},{"Size":12288,"Mallocs":273,"Frees":273},{"Size":13568,"Mallocs":17,"Frees":17},{"Size":14336,"Mallocs":4,"Frees":4},{"Size":16384,"Mallocs":149,"Frees":140},{"Size":18432,"Mallocs":7,"Frees":7},{"Size":19072,"Mallocs":2,"Frees":1}]},
"op_version": 40100,
"peer-id": "a800a499-6820-4c45-8d72-34da4491a2cf",
"pmap": {"base_port":49152,"last_allocated_port":49153},
"raft.status": {"id":"8a41210af6ee50e2","term":2,"vote":"8a41210af6ee50e2","commit":1449,"lead":"8a41210af6ee50e2","raftState":"StateLeader","applied":1449,"progress":{"8a41210af6ee50e2":{"match":1449,"next":1450,"state":"ProgressStateProbe"}},"leadtransferee":"0"},
"store": {"delete": 18, "get": 331, "put": 1251, "txn": 108},
"sunrpc_clients_connected": 0,
"txn": {"initiated_txn_in_progress": -1, "initiated_txn_success": 17, "txn_ctx_store_commit": 108, "txn_ctx_store_get": 103},
"version": "v4.1.0-164.gite8ebe18"
}
```
[glusterd2.log](https://github.com/gluster/glusterd2/files/2340573/glusterd2.log)
[var-run-glusterd2-bricks-test01-subvol1-brick1-brick.log](https://github.com/gluster/glusterd2/files/2340602/var-run-glusterd2-bricks-test01-subvol1-brick1-brick.log)

### Useful commands

- To get glusterd2 version
    ```
    glusterd2 --version
    ```
- To get ETCD version
    ```
    etcd --version
    ```
- To get output of statedump
    ```
    curl http://glusterd2-IP:glusterd2-Port/statedump
    ```

**Comment by Shrivaibavi** [comment] 2018-08-31 15:29
### Volumes and snapshots went missing after that.

### steps done

``` 
[root@dhcp35-30 ~]# glustercli volume start test01 --force
volume start failed

Response headers:
X-Gluster-Cluster-Id: 63b39a41-c5c8-4518-93ec-4667f987207e
X-Gluster-Peer-Id: a800a499-6820-4c45-8d72-34da4491a2cf
X-Request-Id: 9c8d7168-bb81-45af-9437-867de3252456

Response body:
Transaction step vol-start.StartBricks failed on peer a800a499-6820-4c45-8d72-34da4491a2cf with error: exit status 1

[root@dhcp35-30 ~]# glustercli volume start test01
volume start failed

Response headers:
X-Gluster-Peer-Id: a800a499-6820-4c45-8d72-34da4491a2cf
X-Request-Id: 8f863962-07aa-4b3f-a355-99c6ed3be225
X-Gluster-Cluster-Id: 63b39a41-c5c8-4518-93ec-4667f987207e

Response body:
volume already started

[root@dhcp35-30 ~]# systemctl restart glusterd2

[root@dhcp35-30 ~]# glustercli volume status test01
Volume : test01
Error getting Volume status

Response headers:
X-Request-Id: 9eed6206-2ae5-4627-9ff2-fb424150bfcf
X-Gluster-Cluster-Id: 63b39a41-c5c8-4518-93ec-4667f987207e
X-Gluster-Peer-Id: a800a499-6820-4c45-8d72-34da4491a2cf

Response body:
volume not found

[root@dhcp35-30 ~]# glustercli volume list
+----+------+------+-------+-----------+--------+
| ID | NAME | TYPE | STATE | TRANSPORT | BRICKS |
+----+------+------+-------+-----------+--------+
+----+------+------+-------+-----------+--------+

[root@dhcp35-30 ~]# glustercli snapshot list
+------+---------------+
| NAME | ORIGIN VOLUME |
+------+---------------+
+------+---------------+

[root@dhcp35-30 ~]# lsblk
NAME                                       MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
vda                                        252:0    0  40G  0 disk 
├─vda1                                     252:1    0   1G  0 part /boot
└─vda2                                     252:2    0  39G  0 part 
  ├─centos_dhcp35--30-root                 253:0    0  37G  0 lvm  /
  └─centos_dhcp35--30-swap                 253:1    0   2G  0 lvm  [SWAP]
vdb                                        252:16   0  20G  0 disk 
├─vg1-lvol0                                253:2    0   1G  0 lvm  
├─vg1-pool1_tmeta                          253:3    0   1G  0 lvm  
│ └─vg1-pool1-tpool                        253:5    0  17G  0 lvm  
│   ├─vg1-pool1                            253:6    0  17G  0 lvm  
│   └─vg1-lv1                              253:7    0  17G  0 lvm  /bricks/brick0
└─vg1-pool1_tdata                          253:4    0  17G  0 lvm  
  └─vg1-pool1-tpool                        253:5    0  17G  0 lvm  
    ├─vg1-pool1                            253:6    0  17G  0 lvm  
    └─vg1-lv1                              253:7    0  17G  0 lvm  /bricks/brick0
vdc                                        252:32   0  30G  0 disk 
├─vg--dev--vdc-tp_test01_s1_b1_tmeta       253:8    0   4M  0 lvm  
│ └─vg--dev--vdc-tp_test01_s1_b1-tpool     253:10   0  20M  0 lvm  
│   ├─vg--dev--vdc-tp_test01_s1_b1         253:11   0  20M  0 lvm  
│   ├─vg--dev--vdc-brick_test01_s1_b1      253:12   0  20M  0 lvm  /run/glusterd2/bricks/test01/subvol1/
│   ├─vg--dev--vdc-snap_snap1_test01_s1_b1 253:13   0  20M  0 lvm  /run/glusterd2/snaps/snap1/test01/sub
│   ├─vg--dev--vdc-snap_snap2_test01_s1_b1 253:14   0  20M  0 lvm  
│   ├─vg--dev--vdc-snap_snap3_test01_s1_b1 253:15   0  20M  0 lvm  
│   └─vg--dev--vdc-snap_snap4_test01_s1_b1 253:16   0  20M  0 lvm  
└─vg--dev--vdc-tp_test01_s1_b1_tdata       253:9    0  20M  0 lvm  
  └─vg--dev--vdc-tp_test01_s1_b1-tpool     253:10   0  20M  0 lvm  
    ├─vg--dev--vdc-tp_test01_s1_b1         253:11   0  20M  0 lvm  
    ├─vg--dev--vdc-brick_test01_s1_b1      253:12   0  20M  0 lvm  /run/glusterd2/bricks/test01/subvol1/
    ├─vg--dev--vdc-snap_snap1_test01_s1_b1 253:13   0  20M  0 lvm  /run/glusterd2/snaps/snap1/test01/sub
    ├─vg--dev--vdc-snap_snap2_test01_s1_b1 253:14   0  20M  0 lvm  
    ├─vg--dev--vdc-snap_snap3_test01_s1_b1 253:15   0  20M  0 lvm  
    └─vg--dev--vdc-snap_snap4_test01_s1_b1 253:16   0  20M  0 lvm  
vdd                                        252:48   0  30G  0 disk 
```

**Comment by rafikc30** [comment] 2018-09-03 12:25
From lsblk output, I can clearly see that you are creating an lv of size 20MB, that is not at an optimal value. What happens here is, the lvsize reaches 100%, ie 20MB. Hence the mount point goes into i/o error state. Which will lead the health checker to fail.

We have a check in snapshot create that disallow snapshot creation if lv size is greater than 90%. But here it couldn't catch since the 10% is too small (lvm update the size asynchronously )

**Comment by Shrivaibavi** [comment] 2018-09-04 07:16
@rafikc30 i understood why the health check failed and brick went down

But still the volumes and snapshot went missing from the node that is still mysterious.

**Comment by atinmu** [comment] 2018-09-14 06:17
So what's the conclusion on this issue? Is there anything else we should investigate @rafikc30 ?

**Comment by rafikc30** [comment] 2018-09-14 06:36
@atinmu Though we found why health checker is failing, we don't know what happened to entire etcd store. It seems very unlikely to happen from glusterd.

I think we can close this issue. As far as I remember @Shrivaibavi had tried to reproduce the issue and were not successful. So let's close this issue and in case if we hit it again, we can reopen it.

**Comment by rafikc30** [comment] 2018-09-14 06:53
@Shrivaibavi Can you please close this issue if it is not reproducible?

**Closed** 2018-09-17 11:15 UTC
